[build]
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_FORCE_EDGE_IMAGES = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = [], Country = [], Role = []} 